on:
  pull_request:
    branches:
      - main

permissions:
  contents: read 
  actions: read 

jobs:
  terraform-checks:
    name: 'Terraform Checks'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Format
      run: terraform fmt -check -recursive
    
    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with: 
        framework: terraform